# How to compute attitude of robot

In [ ]:
import numpy as np
import numpy.ma as ma
from coordinates import Coordinate

We know which leg is touching the floor with:
- touching var is a bool array representing if the leg is touching the floor
- mov var is an array of the displacement in X of the leg

In [ ]:
touching = np.array([True, False, True, False])
mov = np.array([-1, -1, -0.5, 0])

We use masked array to work only on the movement of the legs that are touching the floor

In [ ]:
mov_mx_x = ma.masked_array(mov, mask=np.invert(touching))
mov_mx_x

In [ ]:
nb_touching_legs = np.sum(touching)

delta_x = 0  # Represent the change of attitude in X

if np.abs(np.sum(np.sign(mov_mx_x))) == nb_touching_legs:
    # This means the legs are moving in the same direction
    min_mov = mov_mx_x[np.argmin(np.abs(mov_mx_x))]
    delta_x += min_mov
    mov_mx_x -= min_mov

In [ ]:
mov_mx_x

# Actuation repeat same sequence

In [ ]:
steps = 3
actuation = np.concatenate(
    (
        np.linspace(0, 5 * 2, num=steps),
        np.linspace(5 * 2, 0, num=steps)
    ),
    axis=0
)
actuation = np.tile(actuation, 2)

In [ ]:
actuation

# Pandas multi level 

In [1]:
import pandas as pd
import numpy as np

In [39]:
A = [1, 2, 3, 4, 5]
B = [4, 5, 6, 7, 8]
C = [7, 8, 9, 10, 11]
u = [1, 2, 3, 12, 13]
tmp = np.array([u, A, B, C]).T
J1 = pd.DataFrame(tmp, columns=['u', 'A', 'B', 'C'])

In [40]:
J2 = pd.DataFrame(tmp, columns=['u', 'A', 'B', 'C'])
pos = [Coordinate(x=0, y=1), Coordinate(x=0, y=1), Coordinate(x=0, y=1), Coordinate(x=0, y=1), Coordinate(x=0, y=4)]
tmp = np.array([u, pos]).T
rob = pd.DataFrame(tmp, columns=['u', 'pos'])

C:/Users/glagl/AppData/Local/Temp/xpython_15172/529074524.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  tmp = np.array([u, pos]).T


In [41]:
robot = {}
robot['J1'] = J1
robot['J2'] = J2
robot['rob'] = rob
robot = pd.concat(robot, axis=1)

In [42]:
robot

J1            J2           rob        
    u  A  B   C   u  A  B   C   u     pos
0   1  1  4   7   1  1  4   7   1  [y, x]
1   2  2  5   8   2  2  5   8   2  [y, x]
2   3  3  6   9   3  3  6   9   3  [y, x]
3  12  4  7  10  12  4  7  10  12  [y, x]
4  13  5  8  11  13  5  8  11  13  [y, x]

# Python list of coordinates to list

In [1]:
from coordinates import Coordinate

In [7]:
l = []
l.append(Coordinate(x=0, y=12, z=0))
l.append(Coordinate(x=1, y=2, z=1))

In [8]:
def list_coord2list(list_coordinates):
    """
    Convert a list(Coordinates) to 3 list of axis coordinate
    x[], y[] and z[]
    """
    x = [c.x for c in list_coordinates]
    y = [c.y for c in list_coordinates]
    z = [c.z for c in list_coordinates]

    return x, y, z

In [9]:
t = [[1, 2, 3], list_coord2list(l)]

In [10]:
t

[[1, 2, 3], ([0, 1], [12, 2], [0, 1])]

# Python plane angle

In [2]:
import numpy as np
import numpy.ma as ma

In [47]:
legs_positions = np.array([
    [1, 2, 3], 
    [2, 1, 3],
    [1, 2, 3], 
    [2, 1, 3]
])

touching_legs = [True, False, False, False]


In [43]:
legs_positions[np.where(np.array(touching_legs) == True)]

array([[1, 2, 3],
       [2, 1, 3],
       [2, 1, 3]])

In [44]:
legs_positions[1] - legs_positions[2]

array([ 1, -1,  0])

In [51]:
legs = np.array([1, 2, 3, 4])
touching_legs = np.array([True, False, False, False])
touching_legs_index = np.array([1])
m = np.ones(legs.size, dtype=bool)
m[touching_legs_index] = False
sub_legs = legs[m]

In [52]:
sub_legs

array([1, 3, 4])

In [53]:
np.where(sub_legs < 4)

(array([0, 1], dtype=int64),)

In [61]:
np.concatenate((np.array([1, 2]), None))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 0 dimension(s)

# Rotation from vector solve

In [33]:
import numpy as np
from numpy.linalg import norm
from scipy.spatial.transform import Rotation as R


ModuleNotFoundError: No module named 'scipy'

In [93]:
ground = np.array([-1, 1, 1])
plane = np.array([0, 0, 1])

In [94]:
def roll(v): 
    """
    around x axis, v is [y ,z]
    """
    w = np.array([0, 1])
    return np.sign(np.cross(v, w)) * np.arccos(v.dot(w)/(norm(v)*norm(w)))
def pitch(v): 
    """
    around y axis, v is [x, z]
    """
    w = np.array([0, 1])
    return np.sign(np.cross(v, w)) * np.arccos(v.dot(w)/(norm(v)*norm(w)))

In [95]:
roll(v=np.array([ground[1], ground[2]]))

0.7853981633974484

In [96]:
pitch(v=np.array([ground[0], ground[2]]))

-0.7853981633974484