In [2]:
import numpy as np
from coordinates import Coordinate


In [3]:
touching = [True, False, False, True]
mov = [Coordinate(x=1, y=2, z=3), Coordinate(x=1, y=2, z=3), Coordinate(x=1, y=2, z=3), Coordinate(x=1, y=2, z=3)]

In [35]:
mov = np.array([1, -1, 1, 0])
out = np.where(mov != 0)

In [36]:
out

(array([0, 1, 2], dtype=int64),)

In [37]:
np.sum(np.sign(mov[out]))

1

In [26]:
mov[out]

array([1, 1])

array([1, 1])